services:
  - type: web
    name: photostudio-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here
    repo: https://github.com/ваш_логин/photostudio.git
    branch: main
